# Generated by Django 3.2.6 on 2021-08-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basestudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default=None, upload_to='picture'),
            preserve_default=False,
        ),
    ]
